spring:
	datasource:
		driver-class-name: com.mysql.jdbc.Driver
		username: root
		password: 123456
		url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSLL=false
	jpa:
		show-sql: true
sever:
	context-path: /sell
logging:
	pattern:
		console: "%d - %msg%n"
	file: /var/log/tomcat/sell.log
	